### ISSUE TITLE
Styling master document from stylesheets defined in HTML Imports is deprecated

### ISSUE THREAD

**Issue by JohnRiv** [PolymerElements/iron-flex-layout#128] opened 2017-09-27 21:00 UTC
### Description
When using iron-flex-layout, Chrome Canary displays this warning in the console:

> ⚠️ [Deprecation] Styling master document from stylesheets defined in HTML Imports is deprecated, and is planned to be removed in M65, around March 2018. Please refer to https://goo.gl/EGXzpw for possible migration paths.

### Expected outcome

No warnings should be displayed in the console

### Actual outcome

That warning is displayed

### Live Demo
Go to any page with iron-flex-layout. https://elements.polymer-project.org/guides/flex-layout will do the trick.

### Steps to reproduce

1. HTML Import `iron-flex-layout.html`
2. Open the page in Chrome Canary
3. Check the console

### Browsers Affected

- [x] Chrome
- [ ] Firefox
- [ ] Safari 9
- [ ] Safari 8
- [ ] Safari 7
- [ ] Edge
- [ ] IE 11
- [ ] IE 10

**Comment by notwaldorf** [comment] 2017-09-27 22:35
@azakus Hmm, I thought if we used it in a `custom-style` it was fine. Or, was it not merged in Polymer yet?

**Comment by azakus** [comment] 2017-09-28 18:50
@notwaldorf Not released yet, but this is specifically a dupe of https://github.com/Polymer/polymer/issues/4679

**Closed by azakus** 2017-09-28 18:50 UTC

**Comment by ggriffithsIDBS** [comment] 2017-09-29 11:49
So 10.1.1 just got released but im still seeing this warning all over. Would be so much better if had some idea what files were causing this. Seeing it on my demo pages, with the iron-demo-helpers components. Need to see if its our code or not too.

**Comment by ankushbiswas** [comment] 2018-03-12 18:33
same issue in Google Chrome | 64.0.3282.140 (Official Build) (64-bit)

**Comment by MinwooYu2815** [comment] 2018-10-14 08:07
It doesn't work Firefox Developer Edition too. 👍

**Comment by lulzimfazlija** [comment] 2018-10-21 22:40
I have this issue only in Google Chrome, anyone knows the fix?

**Comment by MinwooYu2815** [comment] 2018-10-21 22:48
I fixed it to use javascript + jquery
But it is slower than HTML Import

this code loads ./templates/header.html at <div id=header>
<script src="Res/jquery-3.3.1.min.js"></script>
<script type="text/javascript">
$(document).ready(function () {
$("#header").load("./templates/header.html")
});
</script>
