### ISSUE TITLE
Update Documentation

### ISSUE THREAD

**Issue by phidias51** [PolymerElements/iron-flex-layout#70] opened 2016-01-19 17:34 UTC
We recently updated to the latest version of iron-flex-layout. We spent the better part of the day trying to figure out why all of our interfaces were suddenly out of kilter.  It turns out that since we make heavy use of the flex CSS classes, the import needed to change to "iron-flex-import/classes/iron-flex-import.html".  The top level documentation for the component (not the guide) should be updated to with a notice that anyone updating to this version needs to make the appropriate path change in their imports.  That kind of breaking change needs to be really obvious and highlighted in the documentation.

**Comment by notwaldorf** [comment] 2016-01-22 07:09
Argh, I'm sorry about your frustration. We are recommending against using the classes versions of `iron-flex-layout`. The problem is that they rely very strongly on the `/deep/` and `::shadow` selectors, which are getting deprecated in Chrome. This is why all the top level docs only mention the mixins versions.

**Comment by phidias51** [comment] 2016-01-22 17:57
@notwaldorf Let me get this straight, are you saying that we need to replace all of the classes we're currently using (in about 100 different files) with mixin references?  I understand the reason behind removing deep and shadow references, but not sure why that means that the classes can't be updated to still work properly.  Doesn't the CSS flex library work (upon which the iron-flex-layout is based), work without regard to deep and shadow?  If so, shouldn't the classes still work without deep and shadow references?

Getting back for a moment to the issue of breaking changes.  Ordinarily that might not be such a problem for refactorable code, but in this case, there is no way to refactor and fix this without a lot of people touching a lot of code.  Do you guys have some sort of migration script in mind, or other means of handling this change?

**Comment by notwaldorf** [comment] 2016-01-22 19:46
We are working on a solution to make classes work properly (I'm bumping this to my top of the list next week) but they still won't work exactly as they do today (mostly because it's a bit expensive to import the entire iron-flex-layout stylesheet in every element, which the `/deep/` approach was avoiding).

We can look at setting up an upgrade script, sure. Let me talk some more with the team next week and figure out what our solution will be. In any case, the deprecation isn't happening for a while.

**Comment by notwaldorf** [comment] 2016-01-28 19:26
Closing as duplicate of https://github.com/PolymerElements/iron-flex-layout/issues/23

**Closed by notwaldorf** 2016-01-28 19:26 UTC
