### ISSUE TITLE
How are we supposed to use iron-flex-layout without /deep/?

### ISSUE THREAD

**Issue by AndreasGalster** [PolymerElements/iron-flex-layout#74] opened 2016-01-30 20:12 UTC
Since deep has been deprecated it's recommended to use mixins in our elements. However, let's say I make use of 10 different flex classes, I'll have to define all of those classes in my element. Even worse, now I have to **remember** defining those classes, so let's say I want to use flex-6, I can't just use it, I need to make sure it's defined. Why isn't there just something like one iron-flex-classes layout.html element that imports **all** the classes by default? 

It seems the iron-flex-classes is supposed to be deprecated soon, so I'm not sure how we're supposed to deal with this? It's some serious overkill having to write all these mixin definitions over, and over, and over, and over (I hope I've made my point) again in each element. 

This might make sense for writing just one re-usable element that needs to be used by other people if you submit your element for customelements.io but for one app that makes use of these mixins over and over again, it's very frustrating. Why don't we define a layout-flex-classes that applies all the mixins, so for example: 

`.flex-4 {
   @apply(--layout-flex-4);
}`

And use that as a shared style that we can easily import into any document that we know will use a lot of these styles? With any large app you'll end up eventually using almost every flex class. Our app is not that big yet and we're already using around half of all the flex mixins, so once that gets vulcanized you'll have all of those classes in one place anyway. I believe it should be easier to import all those classes (which did did with one html import that defines all those classes as described above.

**Comment by notwaldorf** [comment] 2016-02-01 20:27
I have some good news and some slightly less good news.

The good news is that we're still working on a having a `classes` alternative -- the only challenge there is to make sure that you're not importing the entirety of those css selectors all the time, so we're trying to split them off in smaller chunks, that you can import as needed. Here is the PR for that: https://github.com/PolymerElements/iron-flex-layout/pull/32

The less good news is that you **will** have to import the new classes version of `iron-flex-layout` in each of your elements that need to use it. You will not get the magical `/deep/` world, where you were only required to import `iron-flex-layout` once in the application, and it would be available everywhere. But you also won't have to define the same class over and over again.

**Comment by notwaldorf** [comment] 2016-02-01 20:28
Closing as duplicate of https://github.com/PolymerElements/iron-flex-layout/issues/23 (we're trying to have only one tracking item for this)

**Closed by notwaldorf** 2016-02-01 20:28 UTC
